---
title: '0527'
author: '106035070'
date: "2019年5月27日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#checkpoint_3_forcats.R
```{r}
library(tidyverse)
library(tidyquant)

bike_orderlines_tbl <- read_rds("data_wrangled_student/bike_orderlines.rds")

bike_orderlines_tbl
```
# 1.0 Factor Basics ----
# 2.0 Motivating Example -----
```{r}
# Manipulation
sales_by_cat_2_tbl <- bike_orderlines_tbl %>%
    
    select(category_2, total_price) %>%
    
    group_by(category_2) %>%
    summarize(sales = sum(total_price)) %>%
    ungroup() %>%
    
    arrange(desc(sales)) %>%
    
    mutate(category_2 = category_2 %>% as_factor() %>% fct_rev())

# Plotting
sales_by_cat_2_tbl %>%
    ggplot(aes(x = sales, y = category_2)) +
    geom_point(size = 5, color = "#2c3e50") +
    labs(title = "Sales By Category 2") +
    scale_x_continuous(labels = scales::dollar_format()) +
    theme_tq() +
    expand_limits(x = 0)

plot_sales <- function(data) {
    data %>%
        ggplot(aes(x = sales, y = category_2)) +
        geom_point(size = 5, color = "#2c3e50") +
        labs(title = "Sales By Category 2") +
        scale_x_continuous(labels = scales::dollar_format()) +
        theme_tq() +
        expand_limits(x = 0)
}

sales_by_cat_2_tbl %>%
    plot_sales()
```
# 3.0 Forcats Basics ----
```{r}
# 3.1 Inspecting Factors ----

# Vector
sales_by_cat_2_tbl %>% pull(category_2) %>% levels()

sales_by_cat_2_tbl %>% pull(category_2) %>% as.numeric()

# Tibble

sales_by_cat_2_tbl %>%
    mutate(category_2 = category_2 %>% fct_rev() %>% fct_rev()) %>%
    mutate(
        label = category_2 %>% as.character(),
        value = category_2 %>% as.numeric()
    )

# 3.2 Creating Factors: as_factor() vs as.factor() ----

sales_by_cat_2_tbl %>%
    mutate(
        category_2           = as.character(category_2),
        category_2_as_factor = as_factor(category_2) %>% as.numeric(),
        category_2_as.factor = as.factor(category_2) %>% as.numeric()
    )



# 3.3 Reordering Factors: fct_reorder() and fct_rev() ----

sales_by_cat_2_tbl %>%
    arrange(desc(sales)) %>%
    mutate(sales_negative = -sales) %>%
    mutate(
        category_2 = category_2 %>% fct_reorder(sales_negative),
        values     = category_2 %>% as.numeric()) %>%
    
    plot_sales()





# 3.4 Time-Based Reordering: fct_reorder2() ----


sales_by_cat_2_q_tbl <- bike_orderlines_tbl %>%
    
    mutate(order_date = order_date %>% floor_date("quarter") %>% ymd()) %>%
    
    group_by(category_2, order_date) %>%
    summarise(sales = sum(total_price)) %>%
    ungroup()

sales_by_cat_2_q_tbl


sales_by_cat_2_q_tbl %>%
    
    mutate(category_2 = category_2 %>% fct_reorder2(order_date, sales)) %>%
    
    ggplot(aes(x = order_date, y = sales, color = category_2)) +
    geom_point() +
    geom_line() +
    facet_wrap(~ category_2) +
    
    theme_tq() +
    scale_color_tq() +
    scale_y_continuous(labels = scales::dollar_format(scale = 1e-6, suffix = "M"))


# 3.5 Creating "Other" Category - fct_lump() & fct_relevel() ----

sales_by_cat_2_tbl %>%
    
    mutate(category_2 = category_2 %>% fct_lump(n = 6, 
                                                w = sales, 
                                                other_level = "All Other Bike Categories")) %>%
    
    group_by(category_2) %>%
    summarize(sales = sum(sales)) %>%
    
    mutate(category_2 = category_2 %>% fct_relevel("All Other Bike Categories", after = 0)) %>%
    
    plot_sales()
```


# 02_ggplot2_geometries_1.R
```{r}
library(tidyverse)
library(lubridate)
library(tidyquant)

bike_orderlines_tbl <- read_rds("data_wrangled_student/bike_orderlines.rds")

glimpse(bike_orderlines_tbl)
```
# 1.0 Point / Scatter Plots ----
```{r}
# Data Manipulation
order_value_tbl <- bike_orderlines_tbl %>%
    
    select(order_id, order_line, total_price, quantity) %>%
    
    group_by(order_id) %>%
    summarize(
        total_quantity = sum(quantity),
        total_price    = sum(total_price)
    ) %>%
    ungroup()

# Scatter Plot
order_value_tbl %>%
    
    ggplot(aes(x = total_quantity, y = total_price)) +
    
    geom_point(alpha = 0.5, size = 2) +
    geom_smooth(method = "lm", se = FALSE)
```
# 2.0 Line Plots ----
```{r}
# Data Manipulation
revenue_by_month_tbl <- bike_orderlines_tbl %>%
    
    select(order_date, total_price) %>%
    
    mutate(year_month = floor_date(order_date, "months") %>% ymd()) %>%
    
    group_by(year_month) %>%
    summarize(revenue = sum(total_price)) %>%
    ungroup()

# Line Plot
revenue_by_month_tbl %>%
    
    ggplot(aes(year_month, revenue)) +
    
    geom_line(size = 0.5, linetype = 1) +
    geom_smooth(method = "loess", span = 0.2)
```
# 3.0 Bar / Column Plots ----
```{r}
# Data Manipulation
revenue_by_category_2_tbl <- bike_orderlines_tbl %>%
    
    select(category_2, total_price) %>%
    
    group_by(category_2) %>%
    summarize(revenue = sum(total_price)) %>%
    ungroup()

# Bar Plot
revenue_by_category_2_tbl %>%
    
    mutate(category_2 = category_2 %>% as_factor() %>% fct_reorder(revenue)) %>%
    
    ggplot(aes(category_2, revenue)) +
    
    geom_col(fill = "#2c3e50") + 
    coord_flip()
```
